ROLLBACK;

BEGIN;

-- Kafka 관련 테이블 (의존성 역순)
DROP TABLE IF EXISTS stock_history CASCADE;
DROP TABLE IF EXISTS product_daily_stats CASCADE;
DROP TABLE IF EXISTS daily_sales CASCADE;
DROP TABLE IF EXISTS processed_events CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;

-- 기존 테이블
DROP TABLE IF EXISTS flash_sale_queue_entries CASCADE;
DROP TABLE IF EXISTS flash_sales CASCADE;
DROP TABLE IF EXISTS price_alerts CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS category CASCADE;

DROP TYPE IF EXISTS flash_queue_status;
-- UUID 생성용 (user_sessions에서 사용)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enum 타입 생성 (flash_sale_queue_entries.status용)
CREATE TYPE flash_queue_status AS ENUM ('WAITING', 'ADMITTED', 'EXPIRED', 'LEFT');

-- 1) users
CREATE TABLE users (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(30)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  email        VARCHAR(255) NOT NULL UNIQUE,
  role         VARCHAR(20)  NOT NULL DEFAULT 'normal-user',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_users_username ON users (username);
CREATE INDEX ix_users_email ON users (email);

-- 2) category (products보다 먼저 생성)
CREATE TABLE category (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(50) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  icon         TEXT,
  description  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_category_name ON category (name);

-- 기본 카테고리 데이터 (icon은 나중에 MinIO 업로드 후 추가)
INSERT INTO category (name, display_name, icon) VALUES
('food',        '식품',         'http://192.168.19.143:30222/category/food.jpeg'),
('living',      '생활용품',      'http://192.168.19.143:30222/category/living.jpeg'),
('beauty',      '뷰티',         'http://192.168.19.143:30222/category/beauty.jpeg'),
('interior',    '인테리어',      'http://192.168.19.143:30222/category/interior.jpeg'),
('electronics', '가전/디지털',    'http://192.168.19.143:30222/category/electronics.jpeg'),
('kitchen',     '주방용품',      'http://192.168.19.143:30222/category/kitchen.jpeg'),
('pet',         '반려동물',      'http://192.168.19.143:30222/category/pet.jpeg'),
('sports',      '스포츠',        'http://192.168.19.143:30222/category/sports.jpeg'),
('books',       '도서/음반',     'http://192.168.19.143:30222/category/books.jpeg'),
('health',      '헬스/건강',     'http://192.168.19.143:30222/category/health.jpeg');

-- 3) products
CREATE TABLE products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(200) NOT NULL,
  brand         VARCHAR(100) NOT NULL,
  category_id   BIGINT NOT NULL,

  original_price INT NOT NULL,
  discount_percent INT NOT NULL DEFAULT 0,

  image         TEXT,
  view_count    INT NOT NULL DEFAULT 0,

  free_shipping BOOLEAN NOT NULL DEFAULT FALSE,
  stock         INT NOT NULL DEFAULT 0,
  is_sold_out   BOOLEAN NOT NULL DEFAULT FALSE,
  sold_out_at   TIMESTAMPTZ,

  description   TEXT,
  depletion_at  TIMESTAMPTZ,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT price_nonneg CHECK (original_price >= 0),
  CONSTRAINT discount_range CHECK (discount_percent >= 0 AND discount_percent <= 100),
  CONSTRAINT stock_nonneg CHECK (stock >= 0),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE INDEX ix_products_name ON products (name);
CREATE INDEX ix_products_brand ON products (brand);
CREATE INDEX ix_products_category_id ON products (category_id);
CREATE INDEX ix_products_sold_out ON products (is_sold_out, category_id);

-- 4) user_sessions
CREATE TABLE user_sessions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,

  CONSTRAINT fk_user_sessions_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ix_user_sessions_user_id ON user_sessions (user_id);
CREATE INDEX ix_user_sessions_valid ON user_sessions (user_id, expires_at, revoked_at);

-- 5) carts
CREATE TABLE carts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_carts_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ix_carts_user_id ON carts (user_id);

-- 6) cart_items
CREATE TABLE cart_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id    BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity   INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_cart_items_cart_id_carts
    FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,

  CONSTRAINT fk_cart_items_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,

  CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
  CONSTRAINT qty_pos CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX ix_cart_items_product_id ON cart_items (product_id);

-- 7) orders  (ORM 확장 버전 + Kafka 이벤트 지원)
CREATE TABLE orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,

  order_number     VARCHAR(36) NOT NULL UNIQUE,

  items_amount     INT NOT NULL,
  total_amount     INT NOT NULL,

  shipping_fee     INT NOT NULL DEFAULT 0,
  shipping_address TEXT NOT NULL,

  -- Kafka 이벤트 추적용 (ORDER_PAID, ORDER_CANCELED)
  status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',   -- PENDING/PAID/CANCELED
  paid_at          TIMESTAMPTZ,
  canceled_at      TIMESTAMPTZ,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_orders_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT amounts_nonneg
    CHECK (items_amount >= 0 AND shipping_fee >= 0 AND total_amount >= 0),

  CONSTRAINT total_eq_sum
    CHECK (total_amount = items_amount + shipping_fee),

  CONSTRAINT chk_order_status
    CHECK (status IN ('PENDING','PAID','CANCELED'))
);

CREATE INDEX ix_orders_user_id ON orders (user_id);
CREATE INDEX ix_orders_order_number ON orders (order_number);
CREATE INDEX ix_orders_status ON orders (status, created_at);

-- 8) order_items
CREATE TABLE order_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT NOT NULL,
  product_id    BIGINT NOT NULL,

  name_snapshot  VARCHAR(200) NOT NULL,
  price_snapshot INT NOT NULL,
  quantity       INT NOT NULL,

  CONSTRAINT fk_order_items_order_id_orders
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,

  CONSTRAINT fk_order_items_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,

  CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
  CONSTRAINT qty_pos CHECK (quantity > 0),
  CONSTRAINT price_nonneg CHECK (price_snapshot >= 0)
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_items_product_id ON order_items (product_id);

-- 9) price_alerts
CREATE TABLE price_alerts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,

  target_price INT,
  enabled     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_price_alerts_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT fk_price_alerts_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,

  CONSTRAINT uq_price_alerts_user_product UNIQUE (user_id, product_id),
  CONSTRAINT target_nonneg CHECK (target_price IS NULL OR target_price >= 0)
);

CREATE INDEX ix_price_alerts_user_id ON price_alerts (user_id);
CREATE INDEX ix_price_alerts_product_id ON price_alerts (product_id);

-- 10) flash_sales
CREATE TABLE flash_sales (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,

  starts_at  TIMESTAMPTZ NOT NULL,
  ends_at    TIMESTAMPTZ NOT NULL,
  capacity   INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_flash_sales_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,

  CONSTRAINT capacity_pos CHECK (capacity > 0),
  CONSTRAINT time_range CHECK (ends_at > starts_at)
);

CREATE INDEX ix_flash_sales_product_id ON flash_sales (product_id);

-- 11) flash_sale_queue_entries (재참가 지원 구조)
CREATE TABLE flash_sale_queue_entries (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flash_sale_id BIGINT NOT NULL,
  user_id       BIGINT NOT NULL,

  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  status        flash_queue_status NOT NULL DEFAULT 'WAITING',

  -- 상태별 타임스탬프 (재참가 지원 + 이력 추적)
  admitted_at   TIMESTAMPTZ,
  left_at       TIMESTAMPTZ,
  expires_at    TIMESTAMPTZ,

  CONSTRAINT fk_flash_queue_flash_sale_id_flash_sales
    FOREIGN KEY (flash_sale_id) REFERENCES flash_sales(id) ON DELETE CASCADE,

  CONSTRAINT fk_flash_queue_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT status_allowed CHECK (status IN ('WAITING','ADMITTED','EXPIRED','LEFT'))
);

CREATE INDEX ix_flash_queue_flash_sale_id ON flash_sale_queue_entries (flash_sale_id);
CREATE INDEX ix_flash_queue_user_id ON flash_sale_queue_entries (user_id);
CREATE INDEX ix_flash_queue_sale_joined ON flash_sale_queue_entries (flash_sale_id, joined_at);
CREATE INDEX ix_flash_queue_status ON flash_sale_queue_entries (flash_sale_id, status, joined_at);

-- Partial Unique Index: 활성 상태(LEFT/EXPIRED 아님)인 경우만 중복 방지
CREATE UNIQUE INDEX ux_flash_queue_user_active
  ON flash_sale_queue_entries(flash_sale_id, user_id)
  WHERE left_at IS NULL AND status IN ('WAITING','ADMITTED');


-- =====================================================================
-- Kafka Event-Driven Architecture 관련 테이블
-- =====================================================================

-- 12) outbox_events (Transactional Outbox Pattern)
CREATE TABLE outbox_events (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- 이벤트 식별
  aggregate_type  VARCHAR(50) NOT NULL,   -- 'ORDER', 'PRODUCT', 'STOCK' 등
  aggregate_id    BIGINT NOT NULL,
  event_type      VARCHAR(50) NOT NULL,   -- 'ORDER_PAID', 'PRODUCT_UPDATED' 등
  payload         JSONB NOT NULL,

  -- Kafka 토픽 라우팅
  topic           VARCHAR(100),

  -- Publisher 상태 관리
  status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',   -- PENDING/PROCESSING/PUBLISHED/FAILED
  retry_count     INT NOT NULL DEFAULT 0,
  error_message   TEXT,

  -- Publisher 동시성 제어
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_at       TIMESTAMPTZ,
  locked_by       VARCHAR(100),

  -- 타임스탬프
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at    TIMESTAMPTZ,

  CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING','PROCESSING','PUBLISHED','FAILED'))
);

CREATE INDEX ix_outbox_aggregate ON outbox_events (aggregate_type, aggregate_id);
-- Publisher 재시도용 인덱스 (PENDING + FAILED 모두 지원)
CREATE INDEX ix_outbox_status_next_attempt ON outbox_events (status, next_attempt_at) WHERE status IN ('PENDING','FAILED');
CREATE INDEX ix_outbox_created_at ON outbox_events (created_at);


-- 13) processed_events (Consumer 멱등성 - 중복 처리 방지)
CREATE TABLE processed_events (
  consumer_name VARCHAR(100) NOT NULL,
  event_id      UUID NOT NULL,
  processed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_processed_events PRIMARY KEY (consumer_name, event_id)
);

CREATE INDEX ix_processed_events_processed_at ON processed_events (processed_at);


-- 14) stock_history (재고 변동 이력 - 감사 로그)
CREATE TABLE stock_history (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 연관 엔티티
  product_id    BIGINT NOT NULL,
  order_id      BIGINT,

  -- 이벤트 추적
  event_id      UUID,
  reason        VARCHAR(50) NOT NULL,   -- 'ORDER_PAID', 'ORDER_CANCELED', 'RESTOCKED'

  -- 재고 스냅샷
  stock_before  INT NOT NULL,
  stock_after   INT NOT NULL,
  delta         INT NOT NULL,           -- +10 or -5

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_stock_history_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,

  CONSTRAINT fk_stock_history_order_id_orders
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,

  CONSTRAINT chk_stock_delta CHECK (stock_after = stock_before + delta)
);

CREATE INDEX ix_stock_history_product_id ON stock_history (product_id);
CREATE INDEX ix_stock_history_product_created ON stock_history (product_id, created_at);
CREATE INDEX ix_stock_history_order ON stock_history (order_id);
CREATE UNIQUE INDEX ix_stock_history_event_idempotency ON stock_history (event_id) WHERE event_id IS NOT NULL;


-- 15) daily_sales (일별 매출 집계)
CREATE TABLE daily_sales (
  date             DATE PRIMARY KEY,
  total_orders     INT NOT NULL DEFAULT 0,
  total_revenue    BIGINT NOT NULL DEFAULT 0,
  unique_customers INT NOT NULL DEFAULT 0,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- 16) product_daily_stats (상품별 일일 통계)
CREATE TABLE product_daily_stats (
  product_id      BIGINT NOT NULL,
  date            DATE NOT NULL,

  view_count      INT NOT NULL DEFAULT 0,
  cart_add_count  INT NOT NULL DEFAULT 0,
  purchase_count  INT NOT NULL DEFAULT 0,
  revenue         BIGINT NOT NULL DEFAULT 0,

  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_product_daily_stats PRIMARY KEY (product_id, date),

  CONSTRAINT fk_product_daily_stats_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX ix_product_daily_stats_date ON product_daily_stats (date);
CREATE INDEX ix_product_daily_stats_product_id ON product_daily_stats (product_id);


-- Products 샘플 데이터
-- 식품 (category_id = 1)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('곰표 우유 식빵 660g', 5000, 19, '곰표', 1, 'http://192.168.19.143:30222/products/1_gompyo_milk.jpeg', 0, true, 3),
('신라면 멀티팩 5개입', 5500, 19, '농심', 1, 'http://192.168.19.143:30222/products/2_shin_ramyun.jpeg', 0, true, 5),
('제주 감귤 3kg', 25000, 21, '제주농협', 1, 'http://192.168.19.143:30222/products/3_3kg_jeju.jpeg', 0, true, 50);

-- 생활용품 (category_id = 2)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('다우니 섬유유연제 3.2L', 19900, 20, '다우니', 2, 'http://192.168.19.143:30222/products/4_downy_fabric.jpeg', 0, true, 150),
('코멧 3겹 화장지 30롤', 18900, 0, '코멧', 2, 'http://192.168.19.143:30222/products/5_comet_3ply.jpeg', 0, true, 200),
('페리오 치약 클리닉 3개', 11900, 25, 'LG생활건강', 2, 'http://192.168.19.143:30222/products/6_perio_toothpaste.jpeg', 0, true, 100);

-- 뷰티 (category_id = 3)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('아이오페 레티놀 세럼 30ml', 65000, 20, 'IOPE', 3, 'http://192.168.19.143:30222/products/7_iope_retinol.jpeg', 0, true, 40),
('라로슈포제 선크림 50ml', 24900, 0, '라로슈포제', 3, 'http://192.168.19.143:30222/products/8_la_rocheposay.jpeg', 0, true, 70);

-- 홈인테리어 (category_id = 4)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('이케아 LED 스탠드', 29900, 0, 'IKEA', 4, 'http://192.168.19.143:30222/products/9_ikea_led.jpeg', 0, false, 30),
('무인양품 소파쿠션', 25000, 20, 'MUJI', 4, 'http://192.168.19.143:30222/products/10_muji_sofa.jpeg', 0, true, 45);

-- 가전디지털 (category_id = 5)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('애플 맥북 에어 M3', 1690000, 6, 'Apple', 5, 'http://192.168.19.143:30222/products/11_apple_macbook.jpeg', 0, true, 15),
('삼성 갤럭시 버즈 FE', 89000, 0, '삼성', 5, 'http://192.168.19.143:30222/products/12_samsung_galaxy.jpeg', 0, true, 80);

-- 주방용품 (category_id = 6)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('휘슬러 압력솥 6L', 350000, 17, '휘슬러', 6, 'http://192.168.19.143:30222/products/13_fissler_pressure.jpeg', 0, true, 20),
('테팔 프라이팬 28cm', 39900, 0, '테팔', 6, 'http://192.168.19.143:30222/products/14_tefal_28cm.jpeg', 0, true, 100),
('코렐 접시세트 16P', 99000, 20, '코렐', 6, 'http://192.168.19.143:30222/products/15_corelle_plate.jpeg', 0, true, 35);

-- 반려동물 (category_id = 7)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('로얄캐닌 사료 3kg', 39900, 18, '로얄캐닌', 7, 'http://192.168.19.143:30222/products/16_royal_canin.jpeg', 0, true, 100),
('하림펫푸드 간식 300g', 8900, 0, '하림', 7, 'http://192.168.19.143:30222/products/17_harim_pet.jpeg', 0, true, 150),
('캣타워 대형 180cm', 120000, 26, '펫모닝', 7, 'http://192.168.19.143:30222/products/18_large_cat.jpeg', 0, false, 20);

-- 스포츠/레저 (category_id = 8)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('나이키 에어맥스 270', 199000, 15, 'Nike', 8, 'http://192.168.19.143:30222/products/19_nike_air.jpeg', 0, true, 40),
('요가매트 NBR 10mm', 19900, 0, '에바', 8, 'http://192.168.19.143:30222/products/20_yoga_mat.jpeg', 0, true, 100),
('캠핑 텐트 4인용', 200000, 21, '코베아', 8, 'http://192.168.19.143:30222/products/21_camping_tent.jpeg', 0, true, 20);

-- 도서/음반 (category_id = 9)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('트렌드 코리아 2025', 19000, 10, '미래의창', 9, 'http://192.168.19.143:30222/products/22_trend_korea.jpeg', 0, true, 200),
('아웃라이어', 15300, 0, '김영사', 9, 'http://192.168.19.143:30222/products/23_outliers.jpeg', 0, true, 150),
('BTS 앨범 정규 4집', 50000, 10, 'HYBE', 9, 'http://192.168.19.143:30222/products/24_bts_4th.jpeg', 0, true, 100);

-- 헬스/건강 (category_id = 10)
INSERT INTO products (name, original_price, discount_percent, brand, category_id, image, view_count, free_shipping, stock) VALUES
('종근당 비타민C 1000', 25000, 20, '종근당', 10, 'http://192.168.19.143:30222/products/25_chong_kun.jpeg', 0, true, 150),
('락토핏 유산균 60포', 23900, 0, '종근당', 10, 'http://192.168.19.143:30222/products/26_lactofit_lactic.jpeg', 0, true, 200),
('홍삼정 에브리타임', 110000, 19, '정관장', 10, 'http://192.168.19.143:30222/products/27_hongsamjeong_everytime.jpeg', 0, true, 60);

COMMIT;

-- 기본 테이블
select * from users;
select * from user_sessions;
select * from category;
select * from products;
select * from carts;
select * from cart_items;
select * from orders;
select * from order_items;
select * from price_alerts;
select * from flash_sales;
select * from flash_sale_queue_entries;

-- Kafka 관련 테이블
select * from outbox_events;
select * from processed_events;
select * from stock_history;
select * from daily_sales;
select * from product_daily_stats;