ROLLBACK;

select * from users;
select * from user_sessions;
select * from products;
select * from carts;
select * from cart_items;
select * from orders;
select * from order_items;
select * from price_alerts;
select * from flash_sales;
select * from flash_sale_queue_entries;


BEGIN;

DROP TABLE IF EXISTS flash_sale_queue_entries CASCADE;
DROP TABLE IF EXISTS flash_sales CASCADE;
DROP TABLE IF EXISTS price_alerts CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS flashqueuestatus;
-- UUID 생성용 (user_sessions에서 사용)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enum 타입 생성 (flash_sale_queue_entries.status용)
CREATE TYPE flashqueuestatus AS ENUM ('WAITING', 'ADMITTED', 'EXPIRED', 'LEFT');

-- 1) users
CREATE TABLE users (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(30)  NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  email        VARCHAR(255) NOT NULL UNIQUE,
  role         VARCHAR(20)  NOT NULL DEFAULT 'normal-user',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_users_username ON users (username);
CREATE INDEX ix_users_email ON users (email);

-- 2) products
CREATE TABLE products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(200) NOT NULL,
  brand         VARCHAR(100) NOT NULL,
  category      VARCHAR(50),

  price         INT NOT NULL,
  original_price INT NOT NULL,

  image         TEXT NOT NULL,
  rating        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  review_count  INT NOT NULL DEFAULT 0,

  free_shipping BOOLEAN NOT NULL DEFAULT FALSE,
  stock         INT NOT NULL DEFAULT 0,

  description   TEXT,
  depletion_at  TIMESTAMPTZ,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT price_nonneg CHECK (price >= 0 AND original_price >= 0),
  CONSTRAINT price_lte_original CHECK (price <= original_price),
  CONSTRAINT stock_nonneg CHECK (stock >= 0)
);

CREATE INDEX ix_products_name ON products (name);
CREATE INDEX ix_products_brand ON products (brand);
CREATE INDEX ix_products_category ON products (category);

-- 3) user_sessions
CREATE TABLE user_sessions (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,

  CONSTRAINT fk_user_sessions_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ix_user_sessions_user_id ON user_sessions (user_id);
CREATE INDEX ix_user_sessions_valid ON user_sessions (user_id, expires_at, revoked_at);

-- 4) carts
CREATE TABLE carts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_carts_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ix_carts_user_id ON carts (user_id);

-- 5) cart_items
CREATE TABLE cart_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id    BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity   INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_cart_items_cart_id_carts
    FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,

  CONSTRAINT fk_cart_items_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,

  CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
  CONSTRAINT qty_pos CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX ix_cart_items_product_id ON cart_items (product_id);

-- 6) orders  (ORM 확장 버전)
CREATE TABLE orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,

  order_number     VARCHAR(36) NOT NULL UNIQUE,
  status           VARCHAR(20) NOT NULL,

  items_amount     INT NOT NULL,
  shipping_fee     INT NOT NULL DEFAULT 0,
  total_amount     INT NOT NULL,

  shipping_address TEXT NOT NULL,

  payment_method   VARCHAR(20),
  payment_status   VARCHAR(20),

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_orders_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT amounts_nonneg
    CHECK (items_amount >= 0 AND shipping_fee >= 0 AND total_amount >= 0),

  CONSTRAINT total_eq_sum
    CHECK (total_amount = items_amount + shipping_fee)
);

CREATE INDEX ix_orders_user_id ON orders (user_id);
CREATE INDEX ix_orders_order_number ON orders (order_number);

-- 7) order_items
CREATE TABLE order_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT NOT NULL,
  product_id    BIGINT NOT NULL,

  name_snapshot  VARCHAR(200) NOT NULL,
  price_snapshot INT NOT NULL,
  quantity       INT NOT NULL,

  CONSTRAINT fk_order_items_order_id_orders
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,

  CONSTRAINT fk_order_items_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,

  CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
  CONSTRAINT qty_pos CHECK (quantity > 0),
  CONSTRAINT price_nonneg CHECK (price_snapshot >= 0)
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_items_product_id ON order_items (product_id);

-- 8) price_alerts
CREATE TABLE price_alerts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,

  target_price INT,
  enabled     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_price_alerts_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT fk_price_alerts_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,

  CONSTRAINT uq_price_alerts_user_product UNIQUE (user_id, product_id),
  CONSTRAINT target_nonneg CHECK (target_price IS NULL OR target_price >= 0)
);

CREATE INDEX ix_price_alerts_user_id ON price_alerts (user_id);
CREATE INDEX ix_price_alerts_product_id ON price_alerts (product_id);

-- 9) flash_sales
CREATE TABLE flash_sales (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,

  starts_at  TIMESTAMPTZ NOT NULL,
  ends_at    TIMESTAMPTZ NOT NULL,
  capacity   INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_flash_sales_product_id_products
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,

  CONSTRAINT capacity_pos CHECK (capacity > 0),
  CONSTRAINT time_range CHECK (ends_at > starts_at)
);

CREATE INDEX ix_flash_sales_product_id ON flash_sales (product_id);

-- 10) flash_sale_queue_entries
CREATE TABLE flash_sale_queue_entries (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flash_sale_id BIGINT NOT NULL,
  user_id       BIGINT NOT NULL,

  joined_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  status        flashqueuestatus NOT NULL DEFAULT 'WAITING',

  CONSTRAINT fk_flash_queue_flash_sale_id_flash_sales
    FOREIGN KEY (flash_sale_id) REFERENCES flash_sales(id) ON DELETE CASCADE,

  CONSTRAINT fk_flash_queue_user_id_users
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

  CONSTRAINT uq_flash_queue_sale_user UNIQUE (flash_sale_id, user_id),
  CONSTRAINT status_allowed CHECK (status IN ('WAITING','ADMITTED','EXPIRED','LEFT'))
);

CREATE INDEX ix_flash_queue_flash_sale_id ON flash_sale_queue_entries (flash_sale_id);
CREATE INDEX ix_flash_queue_user_id ON flash_sale_queue_entries (user_id);
CREATE INDEX ix_flash_queue_sale_joined ON flash_sale_queue_entries (flash_sale_id, joined_at);

COMMIT;
